//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiThanhVien_Roles
    {
        public int MaLoaiTV { get; set; }
        public string MRole { get; set; }
        public string Note { get; set; }
    
        public virtual LoaiThanhVien LoaiThanhVien { get; set; }
        public virtual Role Role { get; set; }
    }
}
